"""empty message

Revision ID: 6bf32da6ab6f
Revises: f4ad0875a34d
Create Date: 2021-01-13 22:01:10.703521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf32da6ab6f'
down_revision = 'f4ad0875a34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('token', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tokens', ['token'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'token')
    op.drop_table('tokens')
    # ### end Alembic commands ###
